/**
 * Bundled example programs for the playground.
 *
 * AUTO-GENERATED by `scripts/generate-examples.ts`. Do not edit by hand.
 * Source files live in `python/examples/*.py`.
 */

export interface Example {
  id: string;
  name: string;
  description: string;
  code: string;
}

export const EXAMPLES: Example[] = [
  {
    id: "hello",
    name: "Hello",
    description: "Hello-world example for the revamped interpreter",
    code: `# Hello-world example for the revamped interpreter
print("Hello, world!")
print("1 + 2 =", 1 + 2)
print("3 * 4 =", 3 * 4)
`,
  },
  {
    id: "sum",
    name: "Sum",
    description: "Sum the numbers 1..10 using a for loop and augmented assignment.",
    code: `# Sum the numbers 1..10 using a for loop and augmented assignment.
# Demonstrates: for-loops, range(), augmented assignment (+=), and print().

total = 0
for i in range(1, 11):
    total += i
print("sum 1..10 =", total)
`,
  },
  {
    id: "factorial",
    name: "Factorial",
    description: "Compute factorial using recursion",
    code: `# Compute factorial using recursion
def fact(n):
    if n <= 1:
        return 1
    return n * fact(n - 1)

for i in range(1, 8):
    print("factorial of", i, "is", fact(i))
`,
  },
  {
    id: "fizzbuzz",
    name: "Fizzbuzz",
    description: "FizzBuzz example - prints numbers 1 to 20, but for multiples of 3 prints \"Fizz\",",
    code: `# FizzBuzz example - prints numbers 1 to 20, but for multiples of 3 prints "Fizz",
# for multiples of 5 prints "Buzz", and for multiples of both 3 and 5 prints "FizzBuzz".
# Demonstrates: modulo (%), if/elif/else chains, and for-loops.

for i in range(1, 21):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)
`,
  },
  {
    id: "lists",
    name: "Lists",
    description: "Demonstrate lists: literals, indexing, for-iteration, and length.",
    code: `# Demonstrate lists: literals, indexing, for-iteration, and length.
# Demonstrates: list literals, indexing, \`len()\`, and \`for ... in ...\`.

nums = [10, 20, 30, 40, 50]
print("first:", nums[0])
print("last:", nums[-1])
print("count:", len(nums))

print("all:")
for n in nums:
    print(" -", n)

# Sum the elements with a for loop.
total = 0
for n in nums:
    total += n
print("sum:", total)
`,
  },
  {
    id: "tuples",
    name: "Tuples",
    description: "Demonstrate tuples: literals, indexing, length, iteration, and concatenation.",
    code: `# Demonstrate tuples: literals, indexing, length, iteration, and concatenation.
# Demonstrates: tuple literals, indexing, \`len()\`, \`+\`, \`for ... in ...\`.

# Tuple literals — note the trailing comma for a 1-tuple.
empty = ()
single = (42,)
pair = ("hello", "world")
point = (3, 7)

print("empty:", empty)
print("single:", single)
print("pair:", pair)
print("point:", point)
print("len(point):", len(point))

# Indexing works just like lists, including negative indices.
print("point[0]:", point[0])
print("point[-1]:", point[-1])

# Tuples are iterable.
print("iterate:")
for value in point:
    print(" -", value)

# Tuples are immutable at the Python level (we use native Python tuples).
# That means \`point[0] = 99\` would raise TypeError — exactly what real
# Python does, which is the design goal of this interpreter.

# Concatenation builds a new tuple.
combined = pair + point
print("combined:", combined)

# Tuples in containers: lists of tuples are very common.
records = [("Alice", 30), ("Bob", 25), ("Carol", 40)]
print("records:")
for record in records:
    print(" -", record[0], "is", record[1])
`,
  },
  {
    id: "dicts",
    name: "Dicts",
    description: "Demonstrate dictionaries: literals, indexing, assignment, iteration, methods.",
    code: `# Demonstrate dictionaries: literals, indexing, assignment, iteration, methods.
# Demonstrates: dict literals, \`len()\`, membership (\`in\`), \`for ... in ...\`,
# and the native dict methods exposed through attribute access.

# A dictionary literal maps string keys to values.
ages = {"alice": 30, "bob": 25, "carol": 40}
print("ages:", ages)
print("len:", len(ages))

# Index by key.
print("alice:", ages["alice"])
print("bob:", ages["bob"])

# \`in\` checks for key membership.
print("alice in ages:", "alice" in ages)
print("dave in ages:", "dave" in ages)

# Adding and overwriting entries via subscript assignment.
ages["dave"] = 35
ages["alice"] = 31
print("after updates:", ages)

# Iteration over a dict yields its keys.
print("keys:")
for name in ages:
    print(" -", name, "is", ages[name])

# Native dict methods: keys(), values(), items().
print("values:", list(ages.values()))
print("count:", len(ages.keys()))

# Nested dicts.
people = {
    "alice": {"age": 30, "city": "Paris"},
    "bob":   {"age": 25, "city": "Berlin"},
}
for name in people:
    info = people[name]
    print(name, "lives in", info["city"], "and is", info["age"])

# Building a dict incrementally.
counts = {}
words = ["the", "cat", "sat", "on", "the", "mat", "the"]
for word in words:
    if word in counts:
        counts[word] = counts[word] + 1
    else:
        counts[word] = 1
print("word counts:")
for word in counts:
    print(" -", word, "appears", counts[word], "time(s)")
`,
  },
  {
    id: "string_methods",
    name: "String Methods",
    description: "Demonstrate string methods: case conversion, trimming, splitting,",
    code: `# Demonstrate string methods: case conversion, trimming, splitting,
# substring search, and replacement.
# Demonstrates: string methods, method chaining, \`len()\`, and \`for ... in ...\`.

text = "  Hello, World!  "
print("Original:", text)
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Stripped:", text.strip())

sentence = "the quick brown fox"
words = sentence.split(" ")
print("Words:")
for w in words:
    print(" -", w)

print("Contains 'quick':", "quick" in sentence)
print("Starts with 'the':", sentence.startswith("the"))
print("Ends with 'fox':", sentence.endswith("fox"))

# Chaining
shouty = "  hello, world  ".strip().upper().replace("WORLD", "Python")
print("Chained:", shouty)
`,
  },
  {
    id: "membership",
    name: "Membership",
    description: "Show off the `in` and `not in` membership operators.",
    code: `# Show off the \`in\` and \`not in\` membership operators.
# Demonstrates: list literals, \`in\`, \`not in\`, and the \`for ... in ...\` loop.

vowels = ["a", "e", "i", "o", "u"]
word = "hello"

print("Letter checks for:", word)
for ch in word:
    if ch in vowels:
        print("  ", ch, "is a vowel")
    else:
        print("  ", ch, "is a consonant")

# Substring check
phrases = ["hello world", "goodbye", "help me", "oh no"]
print("\\nSubstring 'help' in:")
for p in phrases:
    if "help" in p:
        print("  yes:", p)
    else:
        print("  no: ", p)

# \`not in\` - guard against unsafe input
allowed = ["yes", "y", "ok"]
user_input = "nope"
if user_input not in allowed:
    print("\\nSorry,", user_input, "is not a valid answer.")
`,
  },
  {
    id: "break_continue",
    name: "Break Continue",
    description: "Demonstrate `break` and `continue` for early-exit and skip-iteration in",
    code: `# Demonstrate \`break\` and \`continue\` for early-exit and skip-iteration in
# both \`for\` and \`while\` loops.
# Demonstrates: \`break\`, \`continue\`, \`for ... in ...\`, \`while\`, and \`if\`.

# \`break\` exits the loop early.
print("First three numbers:")
for i in range(10):
    if i == 3:
        break
    print(" ", i)

# \`continue\` skips the rest of the current iteration.
print("\\nOdd numbers up to 10:")
for i in range(10):
    if i % 2 == 0:
        continue
    print(" ", i)

# Same idea, but in a while loop.
print("\\nFirst three powers of 2:")
n = 1
count = 0
while True:
    if n > 16:
        break
    print(" ", n)
    n *= 2
    count += 1
    if count >= 3:
        break
`,
  },
  {
    id: "primes",
    name: "Primes",
    description: "Print the prime numbers up to 30.",
    code: `# Print the prime numbers up to 30.
# Demonstrates: for-loops, if/elif/else, modulo (%), and \`not\`.

n = 2
while n <= 30:
    # Use a sentinel to remember whether we found a divisor.
    divisor = 0
    for d in range(2, n):
        if n % d == 0:
            divisor = d
    if not divisor:
        print(n, "is prime")
    n += 1
`,
  },
  {
    id: "two_sum",
    name: "Two Sum",
    description: "LeetCode 1 — Two Sum",
    code: `# LeetCode 1 — Two Sum
# Given an array of integers and a target, return indices of the two
# numbers that add up to the target.
#
# Approach: for each number, check if its complement (target - num) has
# been seen before. If yes, return the stored index and the current index.
# If no, store the number and its index. O(n) time, O(n) space.

def two_sum(nums, target):
    seen = {}  # maps number -> most-recent index
    for i in range(len(nums)):
        complement = target - nums[i]
        if complement in seen:
            return [seen[complement], i]
        seen[nums[i]] = i
    return []  # no solution (won't happen for valid LeetCode input)


# ---- Tests ----
print("Test 1:", two_sum([2, 7, 11, 15], 9))   # [0, 1]   2+7=9
print("Test 2:", two_sum([3, 2, 4], 6))         # [1, 2]   2+4=6
print("Test 3:", two_sum([3, 3], 6))            # [0, 1]   3+3=6
print("Test 4:", two_sum([1, 5, 3, 7], 10))     # [2, 3]   3+7=10
print("Test 5:", two_sum([-1, -2, -3, -4, -5], -8))  # [2, 4]  -3+-5=-8
`,
  },
  {
    id: "add_binary",
    name: "Add Binary",
    description: "LeetCode 67 — Add Binary",
    code: `# LeetCode 67 — Add Binary
# Given two binary strings a and b, return their sum as a binary
# string. The inputs are non-empty and contain only '0' and '1'.
#
# Approach: walk both strings from the right end, like grade-school
# addition. At each position sum the two bits plus the carry, write
# the new least-significant bit to the output, and propagate the
# carry. We use a helper to convert a single character to an int.
#
# Since this interpreter doesn't expose int(ch), we hand-roll it.

def char_to_digit(c):
    if c == "0":
        return 0
    if c == "1":
        return 1
    return 0  # unreachable for valid input


def digit_to_char(d):
    if d == 0:
        return "0"
    return "1"


def add_binary(a, b):
    i = len(a) - 1
    j = len(b) - 1
    carry = 0
    # Build the answer right-to-left, then reverse.
    out = ""
    while i >= 0 or j >= 0 or carry != 0:
        da = 0
        db = 0
        if i >= 0:
            da = char_to_digit(a[i])
            i = i - 1
        if j >= 0:
            db = char_to_digit(b[j])
            j = j - 1
        total = da + db + carry
        carry = total // 2
        out = out + digit_to_char(total % 2)
    # Reverse the string.
    rev = ""
    for k in range(len(out) - 1, -1, -1):
        rev = rev + out[k]
    return rev


# ---- Tests ----
print(add_binary("11", "1"))          # "100"
print(add_binary("1010", "1011"))     # "10101"
print(add_binary("0", "0"))           # "0"
print(add_binary("1", "1"))           # "10"
print(add_binary("1111", "1111"))     # "11110"
print(add_binary("1010", "0"))        # "1010"
print(add_binary("0", "1010"))        # "1010"
print(add_binary("1", "1111"))        # "10000"
print(add_binary("100", "110010"))    # "110110"
print(add_binary("111111", "1"))      # "1000000"
`,
  },
  {
    id: "anagram",
    name: "Anagram",
    description: "LeetCode 242 — Valid Anagram",
    code: `# LeetCode 242 — Valid Anagram
# Determine if two strings are anagrams of each other (same letters
# in any order). Approach: count letter frequencies in both strings
# and compare the histograms. O(n) time, O(1) space (alphabet size).

def is_anagram(s, t):
    if len(s) != len(t):
        return False
    counts = {}
    for ch in s:
        if ch in counts:
            counts[ch] = counts[ch] + 1
        else:
            counts[ch] = 1
    for ch in t:
        if ch not in counts:
            return False
        counts[ch] = counts[ch] - 1
        if counts[ch] < 0:
            return False
    return True


# ---- Tests ----
print("listen / silent:", is_anagram("listen", "silent"))  # True
print("anagram / nagaram:", is_anagram("anagram", "nagaram"))  # True
print("rat / car:", is_anagram("rat", "car"))  # False
print("aabbcc / abcabc:", is_anagram("aabbcc", "abcabc"))  # True
print("a / b:", is_anagram("a", "b"))  # False
print("ab / ba:", is_anagram("ab", "ba"))  # True
print("abc / abcd:", is_anagram("abc", "abcd"))  # False
print("hello / world:", is_anagram("hello", "world"))  # False
print("Race / care:", is_anagram("Race", "care"))  # False (case matters in this version)
`,
  },
  {
    id: "best_time_to_sell",
    name: "Best Time To Sell",
    description: "LeetCode 121 — Best Time to Buy and Sell Stock",
    code: `# LeetCode 121 — Best Time to Buy and Sell Stock
# Given daily stock prices, find the maximum profit from a single buy
# followed later by a single sell. If no profit is possible, return 0.
# O(n) time, O(1) space: track the lowest price seen so far and the
# best profit at each step.

def max_profit(prices):
    min_price = 9999999999
    best = 0
    for price in prices:
        if price < min_price:
            min_price = price
        profit = price - min_price
        if profit > best:
            best = profit
    return best


# ---- Tests ----
print("[7,1,5,3,6,4]:", max_profit([7, 1, 5, 3, 6, 4]))   # 5  (buy 1, sell 6)
print("[7,6,4,3,1]:", max_profit([7, 6, 4, 3, 1]))         # 0  (no profit)
print("[]:", max_profit([]))                                # 0
print("[2,4,1]:", max_profit([2, 4, 1]))                    # 2  (buy 2, sell 4)
print("[1,2]:", max_profit([1, 2]))                        # 1
print("[3,3,3,3]:", max_profit([3, 3, 3, 3]))              # 0
print("[2,1,2,1,0,1,2]:", max_profit([2, 1, 2, 1, 0, 1, 2]))  # 2 (buy 0, sell 2)
`,
  },
  {
    id: "best_time_to_sell_2",
    name: "Best Time To Sell 2",
    description: "LeetCode 122 — Best Time to Buy and Sell Stock II",
    code: `# LeetCode 122 — Best Time to Buy and Sell Stock II
# As in LC 121, but you may complete as many transactions as you
# like (buy one, sell one, buy again, sell again...). You may not
# hold more than one share at a time.
#
# Approach: greedy — every time tomorrow's price is higher than
# today's, capture that difference. Visually, the total profit is
# the sum of all the upward segments of the price curve.
# O(n) time, O(1) space.

def max_profit_ii(prices):
    profit = 0
    n = len(prices)
    for i in range(1, n):
        diff = prices[i] - prices[i - 1]
        if diff > 0:
            profit = profit + diff
    return profit


# ---- Tests ----
print(max_profit_ii([7, 1, 5, 3, 6, 4]))   # 7  (1->5=4, 3->6=3)
print(max_profit_ii([1, 2, 3, 4, 5]))      # 4  (1->5)
print(max_profit_ii([7, 6, 4, 3, 1]))      # 0  (always down)
print(max_profit_ii([1]))                  # 0
print(max_profit_ii([]))                   # 0
print(max_profit_ii([5, 5, 5, 5]))         # 0
print(max_profit_ii([2, 1, 2, 0, 1]))      # 2  (1->2=1, 0->1=1)
print(max_profit_ii([3, 3, 5, 0, 0, 3, 1, 4]))  # 8 (5->3 later, etc.)
print(max_profit_ii([1, 9, 2, 8, 3, 7]))  # 17
`,
  },
  {
    id: "build_array",
    name: "Build Array",
    description: "LeetCode 1920 — Build Array from Permutation",
    code: `# LeetCode 1920 — Build Array from Permutation
# Given a zero-based permutation nums, build an array of the same
# length where ans[i] = nums[nums[i]].

def build_array(nums):
    n = len(nums)
    ans = []
    for i in range(n):
        ans.append(nums[nums[i]])
    return ans


def show(arr):
    return str(arr)


# ---- Tests ----
print("Test 1:", show(build_array([0, 2, 1, 5, 3, 4])))  # [0,1,2,4,5,3]
print("Test 2:", show(build_array([5, 0, 1, 2, 3, 4])))  # [4,5,0,1,2,3]
print("Test 3:", show(build_array([0])))                 # [0]
print("Test 4:", show(build_array([1, 0]))               )# [0, 1]
print("Test 5:", show(build_array([2, 1, 0])))           # [0, 1, 2]
`,
  },
  {
    id: "climbing_stairs",
    name: "Climbing Stairs",
    description: "LeetCode 70 — Climbing Stairs",
    code: `# LeetCode 70 — Climbing Stairs
# You are climbing a staircase. Each step you can take 1 or 2 stairs.
# How many distinct ways can you reach the top of n stairs?
# Approach: this is the Fibonacci sequence. f(n) = f(n-1) + f(n-2).
# Compute iteratively, keeping only the last two values.
# O(n) time, O(1) space.

def climb_stairs(n):
    if n <= 2:
        return n
    prev2 = 1  # f(1)
    prev1 = 2  # f(2)
    for i in range(3, n + 1):
        cur = prev1 + prev2
        prev2 = prev1
        prev1 = cur
    return prev1


# ---- Tests ----
print("n=1 :", climb_stairs(1))   # 1
print("n=2 :", climb_stairs(2))   # 2
print("n=3 :", climb_stairs(3))   # 3
print("n=4 :", climb_stairs(4))   # 5
print("n=5 :", climb_stairs(5))   # 8
print("n=6 :", climb_stairs(6))   # 13
print("n=10:", climb_stairs(10))  # 89
print("n=20:", climb_stairs(20))  # 10946
print("n=30:", climb_stairs(30))  # 1346269
`,
  },
  {
    id: "concatenation_of_array",
    name: "Concatenation Of Array",
    description: "LeetCode 1929 — Concatenation of Array",
    code: `# LeetCode 1929 — Concatenation of Array
# Given an integer array nums, return an array of length 2n that
# consists of nums concatenated to itself.

def get_concatenation(nums):
    n = len(nums)
    result = []
    for i in range(n):
        result.append(nums[i])
    for i in range(n):
        result.append(nums[i])
    return result


def show(arr):
    return str(arr)


# ---- Tests ----
print("Test 1:", show(get_concatenation([1, 2, 1])))   # [1, 2, 1, 1, 2, 1]
print("Test 2:", show(get_concatenation([1, 3, 2, 1])))# [1, 3, 2, 1, 1, 3, 2, 1]
print("Test 3:", show(get_concatenation([])))           # []
print("Test 4:", show(get_concatenation([5])))          # [5, 5]
print("Test 5:", show(get_concatenation([0, 0, 0])))    # [0, 0, 0, 0, 0, 0]
`,
  },
  {
    id: "contains_duplicate",
    name: "Contains Duplicate",
    description: "LeetCode 217 — Contains Duplicate",
    code: `# LeetCode 217 — Contains Duplicate
# Return True if the array contains any duplicate.
# O(n) time using a set.

def contains_duplicate(nums):
    seen = set()
    for n in nums:
        if n in seen:
            return True
        seen.add(n)
    return False


# ---- Tests ----
print("has dup [1,2,3,1]:", contains_duplicate([1, 2, 3, 1]))   # True
print("has dup [1,2,3,4]:", contains_duplicate([1, 2, 3, 4]))   # False
print("has dup [1,1,1,3,3,4,3,2,4,2]:", contains_duplicate([1, 1, 1, 3, 3, 4, 3, 2, 4, 2]))  # True
print("has dup []:", contains_duplicate([]))                    # False
print("has dup [42]:", contains_duplicate([42]))                # False
print("has dup [0,0]:", contains_duplicate([0, 0]))             # True
`,
  },
  {
    id: "first_unique_char",
    name: "First Unique Char",
    description: "LeetCode 387 — First Unique Character in a String",
    code: `# LeetCode 387 — First Unique Character in a String
# Given a string, find the index of the first non-repeating
# character. If none, return -1.
# Approach: build a frequency map of all chars, then walk the string
# again to find the first one whose count is 1.
# O(n) time, O(k) extra space where k is the alphabet size.

def first_unique_char(s):
    counts = {}
    for i in range(len(s)):
        ch = s[i]
        if ch in counts:
            counts[ch] = counts[ch] + 1
        else:
            counts[ch] = 1
    for i in range(len(s)):
        ch = s[i]
        if counts[ch] == 1:
            return i
    return -1


# ---- Tests ----
print("'leetcode'   :", first_unique_char("leetcode"))   # 0  (l)
print("'loveleetcode':", first_unique_char("loveleetcode"))  # 2  (v)
print("'aabb'       :", first_unique_char("aabb"))       # -1
print("'z'          :", first_unique_char("z"))          # 0
print("'aabbc'      :", first_unique_char("aabbc"))      # 4  (c)
print("'abcabc'     :", first_unique_char("abcabc"))     # -1
print("'stress'     :", first_unique_char("stress"))     # 1  (t)
`,
  },
  {
    id: "group_anagrams",
    name: "Group Anagrams",
    description: "LeetCode 49 — Group Anagrams",
    code: `# LeetCode 49 — Group Anagrams
# Given an array of strings, group the anagrams together.
# Approach: two strings are anagrams iff sorting their characters
# produces the same canonical key. Use a dict to collect groups.
# O(n * k log k) time, where k is the average string length.

def group_anagrams(strs):
    groups = {}
    for s in strs:
        key = sorted(s)  # list of sorted chars
        # Convert list back to string for use as a dict key
        key_str = ""
        for ch in key:
            key_str = key_str + ch
        if key_str not in groups:
            groups[key_str] = []
        groups[key_str].append(s)
    result = []
    for key in groups:
        group_list = []
        for s in groups[key]:
            group_list.append(s)
        result.append(group_list)
    return result


def show_groups(groups):
    """Pretty-print a list of lists of strings."""
    out = "["
    first = True
    for g in groups:
        if not first:
            out = out + ", "
        first = False
        out = out + "["
        inner_first = True
        for s in g:
            if not inner_first:
                out = out + ", "
            inner_first = False
            out = out + "'" + s + "'"
        out = out + "]"
    out = out + "]"
    print(out)


# ---- Tests ----
show_groups(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))
# Expected: [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]]

show_groups(group_anagrams([""]))
# Expected: [[""]]

show_groups(group_anagrams(["a"]))
# Expected: [["a"]]

show_groups(group_anagrams(["abc", "bca", "cab", "xyz", "zyx", "zz"]))
# Expected: [["abc", "bca", "cab"], ["xyz", "zyx"], ["zz"]]

`,
  },
  {
    id: "happy_number",
    name: "Happy Number",
    description: "LeetCode 202 — Happy Number",
    code: `# LeetCode 202 — Happy Number
# A happy number is one where repeatedly replacing the number with
# the sum of the squares of its digits eventually reaches 1. Numbers
# that don't reach 1 enter a cycle.
#
# Approach: a Floyd-style cycle detector. Walk the sequence with a
# \`slow\` pointer (one step) and a \`fast\` pointer (two steps). If
# they ever meet, the sequence is in a cycle and the number is not
# happy. If \`fast\` reaches 1, the number is happy.
#
# Helper: sum of squares of digits, computed manually since we
# don't have a clean way to iterate digits otherwise.

def sum_sq_digits(n):
    total = 0
    while n > 0:
        d = n % 10
        total = total + d * d
        n = n // 10
    return total


def is_happy(n):
    slow = n
    fast = n
    while True:
        slow = sum_sq_digits(slow)
        fast = sum_sq_digits(sum_sq_digits(fast))
        if fast == 1:
            return True
        if slow == fast:
            return False


# ---- Tests ----
print(is_happy(19))     # True  (1^2+9^2=82, 8^2+2^2=68, ..., reaches 1)
print(is_happy(2))      # False (enters the 4, 16, 37, 58, 89, ... cycle)
print(is_happy(1))      # True
print(is_happy(7))      # True
print(is_happy(4))      # False
print(is_happy(10))     # True
print(is_happy(11))     # False
print(is_happy(100))    # True
print(is_happy(999))    # False
print(is_happy(130))    # False
print(is_happy(44))     # True
`,
  },
  {
    id: "length_of_last_word",
    name: "Length Of Last Word",
    description: "LeetCode 58 — Length of Last Word",
    code: `# LeetCode 58 — Length of Last Word
# Given a string s consisting of words and spaces, return the length
# of the last word in the string. A word is a maximal substring of
# non-space characters.
#
# Approach: scan from the end. Skip trailing spaces, then count
# characters until the next space (or the start of the string).
# O(n) time, O(1) extra space.

def length_of_last_word(s):
    n = len(s)
    i = n - 1
    # Skip trailing spaces.
    while i >= 0 and s[i] == " ":
        i = i - 1
    # Count characters of the last word.
    count = 0
    while i >= 0 and s[i] != " ":
        count = count + 1
        i = i - 1
    return count


# ---- Tests ----
print(length_of_last_word("Hello World"))           # 5
print(length_of_last_word("   fly me   to   the moon  "))  # 4
print(length_of_last_word("luffy is still joyboy")) # 6
print(length_of_last_word("a"))                     # 1
print(length_of_last_word(" "))                     # 0
print(length_of_last_word(""))                      # 0
print(length_of_last_word("a "))                    # 1
print(length_of_last_word("day"))                   # 3
print(length_of_last_word("  day  "))               # 3
print(length_of_last_word("    "))                  # 0
print(length_of_last_word("Today is a nice day"))   # 3
`,
  },
  {
    id: "longest_common_prefix",
    name: "Longest Common Prefix",
    description: "LeetCode 14 — Longest Common Prefix",
    code: `# LeetCode 14 — Longest Common Prefix
# Find the longest prefix shared by all strings in the list.
# If no common prefix exists, return "".
# Approach: scan character by character across the first string,
# checking that every other string has the same character at that
# position. Stop on the first mismatch.
# O(S) time, where S is the total number of characters across all strings.

def prefix(s, length):
    """Return the first \`length\` characters of s, manually built up
    since this interpreter does not yet support slice expressions."""
    out = ""
    for i in range(length):
        out = out + s[i]
    return out


def longest_common_prefix(strs):
    if len(strs) == 0:
        return ""
    first = strs[0]
    count = len(strs)
    for i in range(len(first)):
        ch = first[i]
        for j in range(1, count):
            s = strs[j]
            if i >= len(s) or s[i] != ch:
                return prefix(first, i)
    return first


# ---- Tests ----
print(longest_common_prefix(["flower", "flow", "flight"]))  # "fl"
print(longest_common_prefix(["dog", "racecar", "car"]))      # ""
print(longest_common_prefix(["interspecies", "interstellar", "interstate"]))  # "inters"
print(longest_common_prefix(["throne"]))                     # "throne"
print(longest_common_prefix([]))                             # ""
print(longest_common_prefix(["alone"]))                      # "alone"
print(longest_common_prefix(["a"]))                          # "a"
print(longest_common_prefix(["abc", "abc", "abc"]))          # "abc"
print(longest_common_prefix(["abc", "abd", "abe"]))          # "ab"
`,
  },
  {
    id: "majority_element",
    name: "Majority Element",
    description: "LeetCode 169 — Majority Element",
    code: `# LeetCode 169 — Majority Element
# Given an array where one element appears more than n/2 times, find
# that element. It is guaranteed to exist.
# Approach: Boyer-Moore voting. We keep a candidate and a counter.
# On matching the candidate, the counter goes up. On a mismatch,
# it goes down. When the counter hits zero, we adopt the current
# element as the new candidate. At the end, the candidate is the
# majority element.
# O(n) time, O(1) space.

def majority_element(nums):
    candidate = nums[0]
    count = 1
    n = len(nums)
    for i in range(1, n):
        if count == 0:
            candidate = nums[i]
            count = 1
        elif nums[i] == candidate:
            count = count + 1
        else:
            count = count - 1
    return candidate


# ---- Tests ----
print("Test 1:", majority_element([3, 2, 3]))           # 3
print("Test 2:", majority_element([2, 2, 1, 1, 1, 2, 2]))  # 2
print("Test 3:", majority_element([1]))                 # 1
print("Test 4:", majority_element([6, 5, 5]))           # 5
print("Test 5:", majority_element([1, 2, 3, 1, 1, 1]))  # 1
print("Test 6:", majority_element([7, 7, 7, 7, 1, 2, 3]))  # 7
print("Test 7:", majority_element([4]))                 # 4 (single element)
`,
  },
  {
    id: "max_subarray",
    name: "Max Subarray",
    description: "LeetCode 53 — Maximum Subarray",
    code: `# LeetCode 53 — Maximum Subarray
# Given an array of integers, find the contiguous subarray with the
# largest sum. Kadane's algorithm: at each step, either extend the
# current subarray (current + n) or start a new one (n). Track the
# best sum seen.
# O(n) time, O(1) space.

def max_subarray(nums):
    best = nums[0]
    current = nums[0]
    for i in range(1, len(nums)):
        n = nums[i]
        if current + n > n:
            current = current + n
        else:
            current = n
        if current > best:
            best = current
    return best


# ---- Tests ----
print("[-2,1,-3,4,-1,2,1,-5,4]:", max_subarray([-2, 1, -3, 4, -1, 2, 1, -5, 4]))  # 6  (4,-1,2,1)
print("[1]:", max_subarray([1]))                                                       # 1
print("[5,4,-1,7,8]:", max_subarray([5, 4, -1, 7, 8]))                                # 23
print("[-1]:", max_subarray([-1]))                                                     # -1
print("[-1,-2,-3,-4]:", max_subarray([-1, -2, -3, -4]))                                # -1
print("[0,0,0,0]:", max_subarray([0, 0, 0, 0]))                                        # 0
print("[1,2,3,4,5]:", max_subarray([1, 2, 3, 4, 5]))                                   # 15
print("[-2,-1]:", max_subarray([-2, -1]))                                              # -1
`,
  },
  {
    id: "merge_sorted",
    name: "Merge Sorted",
    description: "LeetCode 88 — Merge Sorted Array",
    code: `# LeetCode 88 — Merge Sorted Array
# Merge two sorted arrays nums1 and nums2 into nums1, in sorted order.
# nums1 has enough trailing space (filled with 0s) to hold all elements.
# Approach: three pointers working from the back, so we never overwrite
# values we still need to read. O(m + n) time, O(1) extra space.

def merge(nums1, m, nums2, n):
    i = m - 1       # pointer into nums1 (the real elements)
    j = n - 1       # pointer into nums2
    k = m + n - 1   # write position in nums1 (from the back)

    while i >= 0 and j >= 0:
        if nums1[i] > nums2[j]:
            nums1[k] = nums1[i]
            i -= 1
        else:
            nums1[k] = nums2[j]
            j -= 1
        k -= 1

    # Any leftover elements in nums2 (if any) need to be copied in.
    # Leftovers in nums1 are already in place.
    while j >= 0:
        nums1[k] = nums2[j]
        j -= 1
        k -= 1


# ---- Tests ----
def show(nums):
    return str(nums)


a1 = [1, 2, 3, 0, 0, 0]
merge(a1, 3, [2, 5, 6], 3)
print("Test 1:", show(a1))  # [1, 2, 2, 3, 5, 6]

a2 = [1]
merge(a2, 1, [], 0)
print("Test 2:", show(a2))  # [1]

a3 = [0]
merge(a3, 0, [1], 1)
print("Test 3:", show(a3))  # [1]

a4 = [4, 5, 6, 0, 0, 0]
merge(a4, 3, [1, 2, 3], 3)
print("Test 4:", show(a4))  # [1, 2, 3, 4, 5, 6]

a5 = [-1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0]
merge(a5, 5, [-1, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7], 6)
print("Test 5:", show(a5))  # sorted merge
`,
  },
  {
    id: "missing_number",
    name: "Missing Number",
    description: "LeetCode 268 — Missing Number",
    code: `# LeetCode 268 — Missing Number
# Given an array of n distinct integers in the range [0, n], return
# the only number in the range that is missing from the array.
# Approach: the sum of 0..n is n*(n+1)/2. Subtract every number in
# the array; the remainder is the missing one.
# O(n) time, O(1) space.

def missing_number(nums):
    n = len(nums)
    expected = n * (n + 1) // 2
    actual = 0
    for x in nums:
        actual = actual + x
    return expected - actual


# ---- Tests ----
print("Test 1:", missing_number([3, 0, 1]))     # 2
print("Test 2:", missing_number([0, 1]))        # 2
print("Test 3:", missing_number([9, 6, 4, 2, 3, 5, 7, 0, 1]))  # 8
print("Test 4:", missing_number([0]))           # 1
print("Test 5:", missing_number([1]))           # 0
print("Test 6:", missing_number([4, 2, 1, 0]))  # 3
`,
  },
  {
    id: "move_zeroes",
    name: "Move Zeroes",
    description: "LeetCode 283 — Move Zeroes",
    code: `# LeetCode 283 — Move Zeroes
# Move all 0s to the end of the array while maintaining the relative
# order of the non-zero elements. Must be done in-place.
# Approach: use a write pointer that tracks where the next non-zero
# should go. Iterate through with a read pointer; whenever a non-zero
# is found, write it to the write position and advance write.
# After the loop, fill the rest with zeros.
# O(n) time, O(1) extra space.

def move_zeroes(nums):
    write = 0  # next position to write a non-zero
    n = len(nums)
    for i in range(n):
        if nums[i] != 0:
            nums[write] = nums[i]
            write = write + 1
    # Fill the rest with zeros
    for i in range(write, n):
        nums[i] = 0


def show(nums):
    return str(nums)


# ---- Tests ----
a1 = [0, 1, 0, 3, 12]
move_zeroes(a1)
print("Test 1:", show(a1))  # [1, 3, 12, 0, 0]

a2 = [0]
move_zeroes(a2)
print("Test 2:", show(a2))  # [0]

a3 = [1, 2, 3]
move_zeroes(a3)
print("Test 3:", show(a3))  # [1, 2, 3]  (no zeros)

a4 = [4, 2, 4, 0, 0, 0, 5, 1]
move_zeroes(a4)
print("Test 4:", show(a4))  # [4, 2, 4, 5, 1, 0, 0, 0]

a5 = [0, 0, 1]
move_zeroes(a5)
print("Test 5:", show(a5))  # [1, 0, 0]
`,
  },
  {
    id: "palindrome_number",
    name: "Palindrome Number",
    description: "LeetCode 9 — Palindrome Number",
    code: `# LeetCode 9 — Palindrome Number
# Determine whether an integer is a palindrome (reads the same forwards
# and backwards). Negative numbers are not palindromes because of the
# leading '-'.
#
# Approach: reverse the second half of the digits and compare against
# the first half. Stops in the middle, so it runs in O(log n) time and
# O(1) space.

def is_palindrome(x):
    if x < 0:
        return False
    if x % 10 == 0 and x != 0:
        return False  # any number ending in 0 isn't a palindrome
    reversed_half = 0
    while x > reversed_half:
        reversed_half = reversed_half * 10 + x % 10
        x = x // 10  # integer division
    # x and reversed_half have the same number of digits, or
    # reversed_half has one extra (odd-digit case).
    return x == reversed_half or x == reversed_half // 10


# ---- Tests ----
print("121 is palindrome:", is_palindrome(121))           # True
print("-121 is palindrome:", is_palindrome(-121))         # False
print("10 is palindrome:", is_palindrome(10))             # False
print("0 is palindrome:", is_palindrome(0))               # True
print("12321 is palindrome:", is_palindrome(12321))       # True
print("1234 is palindrome:", is_palindrome(1234))         # False
print("1001 is palindrome:", is_palindrome(1001))         # True
print("1 is palindrome:", is_palindrome(1))               # True
print("1221 is palindrome:", is_palindrome(1221))         # True
`,
  },
  {
    id: "pascals_triangle",
    name: "Pascals Triangle",
    description: "LeetCode 118 — Pascal's Triangle",
    code: `# LeetCode 118 — Pascal's Triangle
# Generate the first n rows of Pascal's Triangle.
# Each element is the sum of the two numbers above it.
# Uses a list of lists (no multi-dimensional literal needed).

def generate(num_rows):
    triangle = []
    for row_num in range(num_rows):
        if row_num == 0:
            triangle.append([1])
            continue
        # Each row starts with a 1
        row = [1]
        # Fill in the interior elements: sum of two above
        prev_row = triangle[row_num - 1]
        for j in range(1, row_num):
            val = prev_row[j - 1] + prev_row[j]
            row.append(val)
        # Each row ends with a 1
        row.append(1)
        triangle.append(row)
    return triangle


def show(triangle):
    for row in triangle:
        print(str(row))


# ---- Tests ----
show(generate(5))
#  [1]
#  [1, 1]
#  [1, 2, 1]
#  [1, 3, 3, 1]
#  [1, 4, 6, 4, 1]

print("---")
show(generate(1))
print("---")
show(generate(0))
print("---")
show(generate(7))
`,
  },
  {
    id: "pascals_triangle_2",
    name: "Pascals Triangle 2",
    description: "LeetCode 119 — Pascal's Triangle II",
    code: `# LeetCode 119 — Pascal's Triangle II
# Given an integer rowIndex, return the rowIndex-th (0-indexed) row
# of Pascal's Triangle. Each interior element is the sum of the two
# elements directly above it; the edges are 1.
#
# Approach: iterative, only keeping the previous row. Compute the
# next row by pairing adjacent elements with a leading 0 and
# trailing 0, e.g.  [0, 1, 3, 3, 1, 0]  ->  [1, 4, 6, 4, 1].
# O(rowIndex^2) time, O(rowIndex) extra space.

def get_row(row_index):
    row = [1]
    for i in range(1, row_index + 1):
        # Build the next row from \`row\` paired with itself shifted by 1.
        # next[j] = row[j - 1] + row[j], with row[-1] treated as 0.
        next_row = [1]
        for j in range(1, i):
            next_row.append(row[j - 1] + row[j])
        next_row.append(1)
        row = next_row
    return row


def show(row):
    return str(row)


# ---- Tests ----
print(show(get_row(0)))   # [1]
print(show(get_row(1)))   # [1, 1]
print(show(get_row(2)))   # [1, 2, 1]
print(show(get_row(3)))   # [1, 3, 3, 1]
print(show(get_row(4)))   # [1, 4, 6, 4, 1]
print(show(get_row(5)))   # [1, 5, 10, 10, 5, 1]
print(show(get_row(6)))   # [1, 6, 15, 20, 15, 6, 1]
print(show(get_row(10)))  # [1, 10, 45, 120, 210, 252, 210, 120, 45, 10, 1]
`,
  },
  {
    id: "plus_one",
    name: "Plus One",
    description: "LeetCode 66 — Plus One",
    code: `# LeetCode 66 — Plus One
# Given an array of digits representing a non-negative integer,
# add 1 to the integer and return the digits.
# Approach: iterate from the least significant digit (right end),
# add 1, propagate any carry. If we carry all the way past the most
# significant digit, prepend a 1.
# O(n) time, O(1) extra space (or O(n) for the rare prepend case).

def plus_one(digits):
    n = len(digits)
    i = n - 1
    while i >= 0 and digits[i] == 9:
        digits[i] = 0
        i = i - 1
    if i < 0:
        # All digits were 9s, e.g. 999 + 1 = 1000
        result = [1]
        for j in range(n):
            result.append(0)
        return result
    digits[i] = digits[i] + 1
    return digits


def show(arr):
    return str(arr)


# ---- Tests ----
print("Test 1:", show(plus_one([1, 2, 3])))        # [1, 2, 4]
print("Test 2:", show(plus_one([4, 3, 2, 1])))     # [4, 3, 2, 2]
print("Test 3:", show(plus_one([9])))              # [1, 0]
print("Test 4:", show(plus_one([9, 9, 9])))        # [1, 0, 0, 0]
print("Test 5:", show(plus_one([0])))              # [1]
print("Test 6:", show(plus_one([8, 9, 9, 9])))     # [9, 0, 0, 0]
print("Test 7:", show(plus_one([1, 9, 0])))        # [1, 9, 1]
`,
  },
  {
    id: "range_sum_query",
    name: "Range Sum Query",
    description: "LeetCode 303 — Range Sum Query - Immutable",
    code: `# LeetCode 303 — Range Sum Query - Immutable
# Given an integer array, support range sum queries:
#   sumRange(i, j) returns the sum of nums[i..j] inclusive.
# Preprocess once with prefix sums so each query is O(1).
#
# Note: the original LeetCode API uses a method on a class instance
# (obj.sumRange(i, j)). This interpreter's class support is minimal
# (no \`self\`, no real instantiation), so we expose the query
# function as a plain closure and call it directly.

def make_range_sum(nums):
    """Return a function \`f(i, j)\` that answers range sum queries."""
    # prefix[k] = sum of nums[0..k-1], with prefix[0] = 0.
    prefix = [0]
    for n in nums:
        prefix.append(prefix[len(prefix) - 1] + n)

    def f(i, j):
        # Guard: if nums was empty, prefix has only one entry [0],
        # and there are no valid i/j pairs. Return 0 as a safe
        # degenerate value. (The LeetCode spec guarantees i/j are
        # in range for non-empty inputs.)
        if len(nums) == 0:
            return 0
        return prefix[j + 1] - prefix[i]

    return f


# ---- Tests ----
arr = make_range_sum([-2, 0, 3, -5, 2, -1])
print("sumRange(0, 2) =", arr(0, 2))   # 1  (-2+0+3)
print("sumRange(2, 5) =", arr(2, 5))   # -1 (3-5+2-1)
print("sumRange(0, 5) =", arr(0, 5))   # -3
print("sumRange(1, 1) =", arr(1, 1))   # 0

a2 = make_range_sum([1, 2, 3, 4, 5])
print("sumRange(0, 4) =", a2(0, 4))   # 15
print("sumRange(2, 3) =", a2(2, 3))   # 7
print("sumRange(4, 4) =", a2(4, 4))   # 5

a3 = make_range_sum([])
print("sumRange(0, 0) on empty =", a3(0, 0))  # 0

a4 = make_range_sum([0, 0, 0, 0])
print("sumRange(0, 3) =", a4(0, 3))   # 0

a5 = make_range_sum([10])
print("sumRange(0, 0) =", a5(0, 0))   # 10

`,
  },
  {
    id: "remove_duplicates_sorted",
    name: "Remove Duplicates Sorted",
    description: "LeetCode 26 — Remove Duplicates from Sorted Array",
    code: `# LeetCode 26 — Remove Duplicates from Sorted Array
# Given a sorted array, remove duplicates in-place so each element
# appears only once. Return the number of unique elements k. The
# first k elements of the array should hold the unique values in
# sorted order; the rest doesn't matter.
#
# Approach: two pointers. \`write\` is the position the next unique
# value should go. \`read\` scans forward. Whenever nums[read] differs
# from the previous value, we copy it to nums[write] and advance
# write. Because the input is sorted, identical values are adjacent.
# O(n) time, O(1) extra space.

def remove_duplicates(nums):
    if len(nums) == 0:
        return 0
    write = 1  # index 0 is always the first unique value
    n = len(nums)
    for read in range(1, n):
        if nums[read] != nums[read - 1]:
            nums[write] = nums[read]
            write = write + 1
    return write


def show(nums):
    return str(nums)


# ---- Tests ----
a1 = [1, 1, 2]
k1 = remove_duplicates(a1)
print("Test 1: k =", k1, " arr =", show(a1))  # 2, [1, 2]

a2 = [0, 0, 1, 1, 1, 2, 2, 3, 3, 4]
k2 = remove_duplicates(a2)
print("Test 2: k =", k2, " arr =", show(a2))  # 5, [0, 1, 2, 3, 4, ...]

a3 = [1]
k3 = remove_duplicates(a3)
print("Test 3: k =", k3, " arr =", show(a3))  # 1, [1]

a4 = []
k4 = remove_duplicates(a4)
print("Test 4: k =", k4, " arr =", show(a4))  # 0, []

a5 = [1, 1, 1, 1]
k5 = remove_duplicates(a5)
print("Test 5: k =", k5, " arr =", show(a5))  # 1, [1, ...]

a6 = [1, 2, 3, 4, 5]
k6 = remove_duplicates(a6)
print("Test 6: k =", k6, " arr =", show(a6))  # 5, [1, 2, 3, 4, 5]

a7 = [-3, -3, -2, -1, -1, 0, 0, 0, 1]
k7 = remove_duplicates(a7)
print("Test 7: k =", k7, " arr =", show(a7))  # 5, [-3, -2, -1, 0, 1, ...]
`,
  },
  {
    id: "remove_element",
    name: "Remove Element",
    description: "LeetCode 27 — Remove Element",
    code: `# LeetCode 27 — Remove Element
# Given an array and a value, remove all occurrences of the value
# in-place. Return the new length k. The order of the remaining
# elements can be changed; only the first k elements matter.
#
# Approach: two pointers. \`write\` tracks where the next kept element
# goes. \`read\` scans the array. If nums[read] != val, copy it to
# nums[write] and advance write. O(n) time, O(1) extra space.

def remove_element(nums, val):
    write = 0
    n = len(nums)
    for read in range(n):
        if nums[read] != val:
            nums[write] = nums[read]
            write = write + 1
    return write


def show(nums):
    return str(nums)


# ---- Tests ----
a1 = [3, 2, 2, 3]
k1 = remove_element(a1, 3)
print("Test 1: k =", k1, " arr =", show(a1))  # 2, [2, 2]

a2 = [0, 1, 2, 2, 3, 0, 4, 2]
k2 = remove_element(a2, 2)
print("Test 2: k =", k2, " arr =", show(a2))  # 5, [0, 1, 3, 0, 4, ...]

a3 = [1]
k3 = remove_element(a3, 1)
print("Test 3: k =", k3, " arr =", show(a3))  # 0, []

a4 = [1, 2, 3, 4]
k4 = remove_element(a4, 5)
print("Test 4: k =", k4, " arr =", show(a4))  # 4, [1, 2, 3, 4]

a5 = [4, 4, 4, 4]
k5 = remove_element(a5, 4)
print("Test 5: k =", k5, " arr =", show(a5))  # 0, [...]

a6 = [1, 1, 1, 1]
k6 = remove_element(a6, 1)
print("Test 6: k =", k6, " arr =", show(a6))  # 0, [...]
`,
  },
  {
    id: "reverse_integer",
    name: "Reverse Integer",
    description: "LeetCode 7 — Reverse Integer",
    code: `# LeetCode 7 — Reverse Integer
# Given a 32-bit signed integer, reverse the digits.
# If the reversed value overflows a 32-bit signed int, return 0.
# Approach: peel off digits with x % 10 and build up the result.
# We use abs() and a sign flag to handle negatives uniformly.

INT_MAX = 2147483647
INT_MIN = -2147483648

def reverse_integer(x):
    sign = 1
    if x < 0:
        sign = -1
        n = -x
    else:
        n = x
    result = 0
    while n > 0:
        digit = n % 10
        result = result * 10 + digit
        n = n // 10
    result = result * sign
    if result < INT_MIN or result > INT_MAX:
        return 0
    return result


# ---- Tests ----
print("123   ->", reverse_integer(123))     # 321
print("-123  ->", reverse_integer(-123))    # -321
print("120   ->", reverse_integer(120))     # 21
print("0     ->", reverse_integer(0))       # 0
print("1534236469 ->", reverse_integer(1534236469))  # 0 (overflow)
print("-2147483412 ->", reverse_integer(-2147483412))# -2143847412
print("1     ->", reverse_integer(1))       # 1
print("10    ->", reverse_integer(10))      # 1
print("1000000 ->", reverse_integer(1000000))  # 1
`,
  },
  {
    id: "reverse_string",
    name: "Reverse String",
    description: "LeetCode 344 — Reverse String",
    code: `# LeetCode 344 — Reverse String
# Write a function that reverses a list of characters in-place.
# We represent a "string" as a list of single-char strings.
# Uses a two-pointer approach: swap elements at the left and right
# pointers, then move inward. O(n) time, O(1) space.

def reverse_string(s):
    left = 0
    right = len(s) - 1
    while left < right:
        temp = s[left]
        s[left] = s[right]
        s[right] = temp
        left = left + 1
        right = right - 1


def to_list(s):
    chars = []
    for i in range(len(s)):
        chars.append(s[i])
    return chars


def show(chars):
    out = ""
    for ch in chars:
        out = out + ch
    return out


# ---- Tests ----
a1 = to_list("hello")
reverse_string(a1)
print(show(a1))  # "olleh"

a2 = to_list("Hannah")
reverse_string(a2)
print(show(a2))  # "hannaH"

a3 = to_list("")
reverse_string(a3)
print(show(a3))  # ""

a4 = to_list("a")
reverse_string(a4)
print(show(a4))  # "a"

a5 = to_list("ab")
reverse_string(a5)
print(show(a5))  # "ba"
`,
  },
  {
    id: "roman_to_int",
    name: "Roman To Int",
    description: "LeetCode 13 — Roman to Integer",
    code: `# LeetCode 13 — Roman to Integer
# Convert a Roman numeral string to its integer value.
# Roman numerals use these symbols:
#   I=1, V=5, X=10, L=50, C=100, D=500, M=1000
# Subtractive pairs (e.g. IV = 4) count as a single value where
# a smaller numeral precedes a larger one.
# Approach: scan left-to-right. If the current value is less than
# the next, subtract it; otherwise add it.
# O(n) time, O(1) space.

def roman_to_int(s):
    # Build a lookup dict
    values = {
        "I": 1, "V": 5, "X": 10, "L": 50,
        "C": 100, "D": 500, "M": 1000,
    }
    total = 0
    n = len(s)
    for i in range(n):
        v = values[s[i]]
        if i + 1 < n and v < values[s[i + 1]]:
            total = total - v
        else:
            total = total + v
    return total


# ---- Tests ----
print("III     ->", roman_to_int("III"))      # 3
print("IV      ->", roman_to_int("IV"))       # 4
print("IX      ->", roman_to_int("IX"))       # 9
print("LVIII   ->", roman_to_int("LVIII"))    # 58   (50 + 5 + 3)
print("MCMXCIV ->", roman_to_int("MCMXCIV"))  # 1994 (1000 + 900 + 90 + 4)
print("MMXX    ->", roman_to_int("MMXX"))     # 2020
print("XL      ->", roman_to_int("XL"))       # 40
print("XC      ->", roman_to_int("XC"))       # 90
print("CD      ->", roman_to_int("CD"))       # 400
print("CM      ->", roman_to_int("CM"))       # 900
print("M       ->", roman_to_int("M"))        # 1000
print("I       ->", roman_to_int("I"))        # 1
`,
  },
  {
    id: "rotate_array",
    name: "Rotate Array",
    description: "LeetCode 189 — Rotate Array",
    code: `# LeetCode 189 — Rotate Array
# Given an array, rotate it to the right by k steps in-place.
# k is non-negative. For example, with k=3:
#   [1, 2, 3, 4, 5, 6, 7]  ->  [5, 6, 7, 1, 2, 3, 4]
#
# Approach: triple-reversal. Reversing the entire array puts each
# element k positions away in the right direction. Then reverse the
# first k elements (to put them in the right order) and reverse the
# remaining n - k elements (to put them in the right order too).
#
# Normalize k with modulo n first so k > n still works.
#
# Since this interpreter does not support slicing, we use a helper
# to reverse nums[i : j] in-place.

def reverse_range(nums, i, j):
    """Reverse nums[i : j] in place using a two-pointer swap.
    The exclusive upper bound j matches Python slice semantics."""
    left = i
    right = j - 1
    while left < right:
        temp = nums[left]
        nums[left] = nums[right]
        nums[right] = temp
        left = left + 1
        right = right - 1


def rotate(nums, k):
    n = len(nums)
    if n == 0:
        return
    k = k % n
    if k == 0:
        return
    reverse_range(nums, 0, n)      # reverse the whole list
    reverse_range(nums, 0, k)      # reverse the first k
    reverse_range(nums, k, n)      # reverse the rest


def show(arr):
    return str(arr)


# ---- Tests ----
a1 = [1, 2, 3, 4, 5, 6, 7]
rotate(a1, 3)
print("Test 1:", show(a1))   # [5, 6, 7, 1, 2, 3, 4]

a2 = [-1, -100, 3, 99]
rotate(a2, 2)
print("Test 2:", show(a2))   # [3, 99, -1, -100]

a3 = [1, 2, 3, 4, 5, 6, 7]
rotate(a3, 0)
print("Test 3:", show(a3))   # [1, 2, 3, 4, 5, 6, 7]  (k=0 no-op)

a4 = [1, 2]
rotate(a4, 3)  # k % n == 1
print("Test 4:", show(a4))   # [2, 1]

a5 = [1]
rotate(a5, 5)
print("Test 5:", show(a5))   # [1]

a6 = []
rotate(a6, 4)
print("Test 6:", show(a6))   # []

a7 = [1, 2, 3, 4, 5]
rotate(a7, 5)  # full rotation
print("Test 7:", show(a7))   # [1, 2, 3, 4, 5]

a8 = [9, 8, 7, 6, 5, 4, 3, 2, 1]
rotate(a8, 4)
print("Test 8:", show(a8))   # [2, 1, 9, 8, 7, 6, 5, 4, 3]
`,
  },
  {
    id: "search_insert",
    name: "Search Insert",
    description: "LeetCode 35 — Search Insert Position",
    code: `# LeetCode 35 — Search Insert Position
# Given a sorted array of distinct ints and a target, return the
# index if the target is found. If not, return the index where it
# would be if it were inserted in order. The algorithm should run
# in O(log n) time.
#
# Approach: classic binary search. We maintain [lo, hi] as the
# candidate range. When the loop exits, lo is the insertion point.

def search_insert(nums, target):
    lo = 0
    hi = len(nums) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            lo = mid + 1
        else:
            hi = mid - 1
    return lo


# ---- Tests ----
print(search_insert([1, 3, 5, 6], 5))    # 2
print(search_insert([1, 3, 5, 6], 2))    # 1
print(search_insert([1, 3, 5, 6], 7))    # 4
print(search_insert([1, 3, 5, 6], 0))    # 0
print(search_insert([1], 0))             # 0
print(search_insert([1], 1))             # 0
print(search_insert([1], 2))             # 1
print(search_insert([1, 3, 5], 4))       # 2
print(search_insert([], 5))               # 0
print(search_insert([1, 3, 5, 7, 9], 8)) # 4
print(search_insert([1, 3, 5, 7, 9], 10))# 5
print(search_insert([1, 3, 5, 7, 9], -1))# 0
`,
  },
  {
    id: "str_str",
    name: "Str Str",
    description: "LeetCode 28 — Find the Index of the First Occurrence",
    code: `# LeetCode 28 — Find the Index of the First Occurrence
# Return the index of the first occurrence of \`needle\` in \`haystack\`,
# or -1 if \`needle\` is not a substring. If needle is empty, return 0.
#
# Approach: naive sliding window. For each starting position i in
# haystack where needle could fit, check character-by-character
# whether needle matches haystack[i : i + m]. We can't use slicing
# in this interpreter, so we compare manually with a helper.
# O((n - m + 1) * m) time, O(1) extra space. For tiny inputs this
# is more than fast enough.

def starts_at(haystack, i, needle, m):
    """Return True iff haystack[i : i + m] == needle."""
    for k in range(m):
        if haystack[i + k] != needle[k]:
            return False
    return True


def str_str(haystack, needle):
    n = len(haystack)
    m = len(needle)
    if m == 0:
        return 0
    if m > n:
        return -1
    last = n - m  # last starting position to try
    for i in range(last + 1):
        if starts_at(haystack, i, needle, m):
            return i
    return -1


# ---- Tests ----
print(str_str("sadbutsad", "sad"))                 # 0
print(str_str("leetcode", "leeto"))                # -1
print(str_str("hello", "ll"))                      # 2
print(str_str("aaaaa", "bba"))                     # -1
print(str_str("abc", ""))                          # 0
print(str_str("", "a"))                            # -1
print(str_str("a", "a"))                           # 0
print(str_str("mississippi", "issip"))             # 4
print(str_str("mississippi", "pi"))                # 9
print(str_str("ababababab", "ababab"))             # 0
print(str_str("ababababab", "babab"))              # 1
print(str_str("abcdef", "abcdef"))                 # 0
print(str_str("abcdef", "abcdefg"))                # -1
`,
  },
  {
    id: "valid_palindrome",
    name: "Valid Palindrome",
    description: "LeetCode 125 — Valid Palindrome",
    code: `# LeetCode 125 — Valid Palindrome
# Determine whether a string is a palindrome, considering only
# alphanumeric characters and ignoring case. Everything else
# (spaces, punctuation) is stripped.
#
# Approach: build a filtered, lowercased string of just alphanumerics,
# then two-pointer scan from both ends comparing characters. O(n) time.
#
# Note: this interpreter doesn't yet expose str.isalnum() / .lower(),
# so we provide a small is_alnum helper and lowercase by ASCII
# arithmetic.

def is_digit(c):
    return c >= "0" and c <= "9"


def is_lower(c):
    return c >= "a" and c <= "z"


def is_upper(c):
    return c >= "A" and c <= "Z"


def to_lower(c):
    if is_upper(c):
        # ASCII trick: ord('A')=65, ord('a')=97, diff = 32
        return chr(ord(c) + 32)
    return c


def is_alnum(c):
    return is_digit(c) or is_lower(c) or is_upper(c)


def filter_chars(s):
    """Strip non-alphanumerics and lowercase what remains."""
    out = ""
    for i in range(len(s)):
        ch = s[i]
        if is_alnum(ch):
            out = out + to_lower(ch)
    return out


def is_palindrome(s):
    cleaned = filter_chars(s)
    n = len(cleaned)
    left = 0
    right = n - 1
    while left < right:
        if cleaned[left] != cleaned[right]:
            return False
        left = left + 1
        right = right - 1
    return True


# ---- Tests ----
print("'A man, a plan, a canal: Panama' :", is_palindrome("A man, a plan, a canal: Panama"))  # True
print("'race a car'                     :", is_palindrome("race a car"))                       # False
print("' '                              :", is_palindrome(" "))                                # True
print("'a'                              :", is_palindrome("a"))                                # True
print("'ab'                             :", is_palindrome("ab"))                               # False
print("'aba'                            :", is_palindrome("aba"))                              # True
print("'abba'                           :", is_palindrome("abba"))                             # True
print("'Was it a car or a cat I saw?'   :", is_palindrome("Was it a car or a cat I saw?"))     # True
print("'tab a cat'                      :", is_palindrome("tab a cat"))                        # False
print("'No lemon, no melon'             :", is_palindrome("No lemon, no melon"))               # True
print("'0P'                             :", is_palindrome("0P"))                               # False
`,
  },
  {
    id: "valid_parentheses",
    name: "Valid Parentheses",
    description: "LeetCode 20 — Valid Parentheses",
    code: `# LeetCode 20 — Valid Parentheses
# Determine if a string of brackets is valid:
#   - Every open bracket has a matching close bracket.
#   - Brackets close in the correct order.
#   - The stack approach: push opens, pop on closes and verify match.
# O(n) time, O(n) space.

def is_valid(s):
    stack = []
    pairs = {
        ")": "(",
        "]": "[",
        "}": "{",
    }
    for ch in s:
        if ch in "([{":
            stack.append(ch)
        elif ch in ")]}":
            if len(stack) == 0:
                return False
            if stack[-1] != pairs[ch]:
                return False
            stack.pop()
    return len(stack) == 0


# ---- Tests ----
print("()        :", is_valid("()"))           # True
print("()[]{}    :", is_valid("()[]{}"))         # True
print("(]        :", is_valid("(]"))           # False
print("([)]      :", is_valid("([)]"))         # False
print("{[]}      :", is_valid("{[]}"))         # True
print("empty     :", is_valid(""))              # True  (empty string is valid)
print("(         :", is_valid("("))            # False
print(")         :", is_valid(")"))            # False
print("(((())))  :", is_valid("(((())))"))      # True
print("([{}])    :", is_valid("([{}])"))        # True
print("((())     :", is_valid("((())"))         # False
`,
  },
];

export const DEFAULT_EXAMPLE_ID = 'hello';

export function getExampleById(id: string): Example | undefined {
  return EXAMPLES.find((e) => e.id === id);
}
