/**
 * Generate src/lib/examples.ts by reading each example from python/examples/.
 *
 * Usage: npx tsx scripts/generate-examples.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Example {
  id: string;
  name: string;
  description: string;
  code: string;
}

const EXAMPLES_DIR = path.join(__dirname, '..', '..', 'python', 'examples');
const OUT_PATH = path.join(__dirname, '..', 'src', 'lib', 'examples.ts');

function makeId(filename: string): string {
  return filename.replace(/\.py$/, '');
}

const entries: Example[] = [];

const files = fs
  .readdirSync(EXAMPLES_DIR)
  .filter((f) => f.endsWith('.py'))
  .sort();

const PREFERRED_ORDER = [
  'hello',
  'sum',
  'factorial',
  'fizzbuzz',
  'lists',
  'tuples',
  'dicts',
  'string_methods',
  'membership',
  'break_continue',
  'primes',
  'two_sum',
];

// First pass: read all examples in alphabetical order.
for (const filename of files) {
  const id = makeId(filename);
  const fullPath = path.join(EXAMPLES_DIR, filename);
  let code = fs.readFileSync(fullPath, 'utf8');
  if (!code.endsWith('\n')) code += '\n';

  // Use the first comment line as the description.
  const lines = code.split('\n');
  let description = '';
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) {
      description = trimmed.replace(/^#\s*/, '');
      break;
    }
  }
  if (!description) description = filename;

  // Human-friendly name: replace underscores with spaces, title-case.
  const name = id
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  entries.push({ id, name, description, code });
}

// Re-order so that the curated examples come first (in PREFERRED_ORDER),
// followed by the rest alphabetically.
entries.sort((a, b) => {
  const aIdx = PREFERRED_ORDER.indexOf(a.id);
  const bIdx = PREFERRED_ORDER.indexOf(b.id);
  if (aIdx === -1 && bIdx === -1) return a.id.localeCompare(b.id);
  if (aIdx === -1) return 1;
  if (bIdx === -1) return -1;
  return aIdx - bIdx;
});

function escapeForTemplate(s: string): string {
  // Escape backticks and `${` so the code can sit safely in a template literal.
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const header = `/**
 * Bundled example programs for the playground.
 *
 * AUTO-GENERATED by \`scripts/generate-examples.ts\`. Do not edit by hand.
 * Source files live in \`python/examples/*.py\`.
 */

export interface Example {
  id: string;
  name: string;
  description: string;
  code: string;
}

export const EXAMPLES: Example[] = [
`;

const footer = `];

export const DEFAULT_EXAMPLE_ID = 'hello';

export function getExampleById(id: string): Example | undefined {
  return EXAMPLES.find((e) => e.id === id);
}
`;

let body = header;
for (const ex of entries) {
  body += `  {\n`;
  body += `    id: ${JSON.stringify(ex.id)},\n`;
  body += `    name: ${JSON.stringify(ex.name)},\n`;
  body += `    description: ${JSON.stringify(ex.description)},\n`;
  body += `    code: \`${escapeForTemplate(ex.code)}\`,\n`;
  body += `  },\n`;
}
body += footer;

fs.writeFileSync(OUT_PATH, body);
console.log(`Wrote ${entries.length} examples to ${OUT_PATH}`);
